### ISSUE TITLE
图像分割

### ISSUE THREAD

**Issue by weidaoquan** [floatingstarZ/GeRSP#2]
请问有关于图像分割相关的下游任务例子吗，谢谢

**Comment by floatingstarZ** [comment]
我们在文中使用PASNet以及DeepLabV3+来进行语义分割的实验，我们使用的数据集是LoveDA数据集

**Comment by weidaoquan** [comment]
请问有相关代码吗

**Comment by floatingstarZ** [comment]
我们就是使用mmsegmentation实现的，在另外一个项目中。如果你想要代码可以留下邮箱

**Comment by weidaoquan** [comment]
我的邮箱是1959254159@qq.com     非常感谢
