### ISSUE TITLE
关于DOTA数据集的配置文件问题

### ISSUE THREAD

**Issue by M1kasali** [floatingstarZ/GeRSP#5]
你好我想问一下我想复现一下GeRSP在DOTA数据集上的结果，但是你的源码上并没有DOTA数据集的配置文件，请问可以提供一下嘛。谢谢

**Comment by floatingstarZ** [comment]
你好，我们DIOR和DOTA的配置是基本一致的，可以参考我们给出的例子，因此我们就没放出来了。区别在：1. 数据集路径(data_root, ann_file, img_prefix)不一样，2. classes是15个类而不是20各类。具体的DOTA配置可以采纳我们的论文。

**Comment by floatingstarZ** [comment]
你可以参考我们新添加的base_settings，在configs_mmdet里，然后做适当修改即可
